* Statistics gathered from test data
  | max width      |        50 |
  | avg width      | 17.291666 |
  | min width      |        10 |
  | std width      | 10.505868 |
  |----------------+-----------|
  | max height     |        50 |
  | avg height     | 16.791666 |
  | min height     |         7 |
  | std height     | 10.517759 |
  |----------------+-----------|
  | max length     |      1000 |
  | avg length     |     180.0 |
  | min length     |        20 |
  | std length     | 163.04715 |

  Units stats

  | distinct units      |                                      |        91 |
  | most popular unit   | MEMBERS (0 0) (:PIVOT 0 0)         |        25 |
  | least popular unit  | MEMBERS (0 0) (0 2) (:PIVOT (0 1)) |         1 |
  | avg number of units |                                      | 2.2527473 |

** MEMBERS (0 0) (0 1) (0 2) (:PIVOT 0 0)
   #+begin_example
     /\                  
     |.|                 
     \/\                 
      | |                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 1) (0 2) (:PIVOT 0 1)
   #+begin_example
     /\                  
     | |                 
     \/\                 
      |.|                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 1) (0 2) (:PIVOT 0 2)
   #+begin_example
     /\                  
     | |                 
     \/\                 
      | |                
     /\/                 
     |.|                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 1) (1 1) (0 2) (:PIVOT 0 1)
   #+begin_example
     /\                  
     | |                 
     \/\/\               
      |.| |              
     /\/\/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 3 times

** MEMBERS (0 0) (0 1) (2 2) (1 1) (0 2) (:PIVOT 1 1)
   #+begin_example
     /\                  
     | |                 
     \/\/\               
      | |.|              
     /\/\/\              
     | | | |             
     \/  \/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 1) (:PIVOT 0 0)
   #+begin_example
     /\                  
     |.|                 
     \/\                 
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 1) (:PIVOT 0 1)
   #+begin_example
     /\                  
     | |                 
     \/\                 
      |.|                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 2) (:PIVOT 0 1)
   #+begin_example
     /\                  
     | |                 
     \/                  
       .                 
     /\                  
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (0 2) (:PIVOT 0 6)
   #+begin_example
     /\                  
     | |                 
     \/                  
     /\                  
     | |                 
     \/                  
      .                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 0) (0 1) (0 2) (:PIVOT 0 1)
   #+begin_example
     /\/\                
     | | |               
     \/\/                
      |.|                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 3 times

** MEMBERS (0 0) (1 0) (0 1) (:PIVOT 0 0)
   #+begin_example
     /\/\                
     |.| |               
     \/\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 2 times

** MEMBERS (0 0) (1 0) (1 1) (0 1) (0 2) (:PIVOT 0 1)
   #+begin_example
     /\/\                
     | | |               
     \/\/\               
      |.| |              
     /\/\/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 0) (1 1) (1 2) (0 3) (:PIVOT 0 1)
   #+begin_example
     /\/\                
     | | |               
     \/\/\               
       .| |              
       /\/               
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 0) (1 1) (:PIVOT 1 0)
   #+begin_example
     /\/\                
     | |.|               
     \/\/\               
        | |              
        \/               
   #+end_example                    
   occurs: 2 times

** MEMBERS (0 0) (1 0) (2 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
     /\/\/\              
     | | | |             
     \/\/\/              
      | |.               
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 0) (2 0) (3 0) (:PIVOT 1 0)
   #+begin_example
     /\/\/\/\            
     | |.| | |           
     \/\/\/\/            
   #+end_example                    
   occurs: 2 times
** MEMBERS (0 0) (1 0) (2 0) (:PIVOT 0 0)
   #+begin_example
     /\/\/\              
     |.| | |             
     \/\/\/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 0) (2 0) (:PIVOT 1 0)
   #+begin_example
     /\/\/\              
     | |.| |             
     \/\/\/              
   #+end_example                    
   occurs: 7 times

** MEMBERS (0 0) (1 0) (2 0) (:PIVOT 2 0)
   #+begin_example
     /\/\/\              
     | | |.|             
     \/\/\/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 0) (:PIVOT 0 0)
   #+begin_example
     /\/\                
     |.| |               
     \/\/                
   #+end_example                    
   occurs: 4 times

** MEMBERS (0 0) (1 0) (:PIVOT 1 0)
   #+begin_example
     /\/\                
     | |.|               
     \/\/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 1) (0 2) (:PIVOT 0 1)
   #+begin_example
     /\                  
     | |                 
     \/ /\               
       .| |              
     /\ \/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (1 1) (0 2) (:PIVOT 0 6)
   #+begin_example
     /\                  
     | |                 
     \/ /\               
        | |              
     /\ \/               
     | |                 
     \/                  
      .                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (2 0) (0 2) (2 2) (:PIVOT 1 1)
   #+begin_example
     /\  /\              
     | | | |             
     \/  \/              
         .               
     /\  /\              
     | | | |             
     \/  \/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (2 0) (:PIVOT 1 0)
   #+begin_example
     /\  /\              
     | |.| |             
     \/  \/              
   #+end_example                    
   occurs: 5 times

** MEMBERS (0 0) (2 0) (:PIVOT 1 5)
   #+begin_example
     /\  /\              
     | | | |             
     \/  \/              
         .               
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 0) (:PIVOT 0 0)
   #+begin_example
     /\                  
     |.|                 
     \/                  
   #+end_example
   occurs: 25 times

** MEMBERS (0 0) (:PIVOT 2 0)
   #+begin_example
     /\                  
     | |  .              
     \/                  
   #+end_example                    
   occurs: 2 times

** MEMBERS (0 0) (:PIVOT 3 0)
   #+begin_example
     /\                  
     | |    .            
     \/                  
   #+end_example                    
   occurs: 10 times

** MEMBERS (0 0) (:PIVOT 4 0)
   #+begin_example
     /\                  
     | |      .          
     \/                  
   #+end_example                    
   occurs: 8 times

** MEMBERS (0 1) (0 0) (1 1) (2 0) (:PIVOT 0 1)
   #+begin_example
     /\  /\              
     | | | |             
     \/\/\/              
      |.| |              
      \/\/               
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 1) (1 1) (2 1) (2 0) (1 2) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
      /\/\/\             
      | |.| |            
      \/\/\/             
       | |               
       \/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 1) (1 1) (3 0) (2 0) (1 2) (:PIVOT 1 1)
   #+begin_example
         /\/\            
         | | |           
      /\/\/\/            
      | |.|              
      \/\/               
       | |               
       \/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 1) (1 1) (3 0) (2 0) (:PIVOT 1 0)
   #+begin_example
         /\/\            
        .| | |           
      /\/\/\/            
      | | |              
      \/\/               
   #+end_example                    
   occurs: 3 times

** MEMBERS (0 1) (1 1) (3 1) (3 0) (2 0) (:PIVOT 1 0)
   #+begin_example
         /\/\            
        .| | |           
      /\/\/\/\           
      | | | | |          
      \/\/  \/           
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 2) (1 2) (3 0) (2 0) (1 1) (:PIVOT 1 1)
   #+begin_example
         /\/\            
         | | |           
        /\/\/            
        |.|              
     /\/\/               
     | | |               
     \/\/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 3) (0 2) (0 0) (1 0) (0 1) (:PIVOT 0 1)
   #+begin_example
     /\/\                
     | | |               
     \/\/                
      |.|                
     /\/                 
     | |                 
     \/\                 
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 3) (0 2) (1 1) (1 0) (0 1) (:PIVOT 0 1)
   #+begin_example
       /\                
       | |               
      /\/\               
      |.| |              
     /\/\/               
     | |                 
     \/\                 
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (0 3) (0 2) (2 0) (1 0) (0 1) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/              
      | |.               
     /\/                 
     | |                 
     \/\                 
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 0) (1 1) (2 1) (:PIVOT 1 0)
   #+begin_example
     /\/\                
     | |.|               
     \/\/\/\             
        | | |            
        \/\/             
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 0) (2 0) (1 1) (:PIVOT 1 0)
   #+begin_example
     /\/\/\              
     | |.| |             
     \/\/\/              
        | |              
        \/               
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 0) (2 0) (2 1) (:PIVOT 1 0)
   #+begin_example
     /\/\/\              
     | |.| |             
     \/\/\/\             
          | |            
          \/             
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 0) (2 0) (3 0) (:PIVOT 1 0)
   #+begin_example
     /\/\/\/\            
     | |.| | |           
     \/\/\/\/            
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 1) (0 2) (:PIVOT 0 1)
   #+begin_example
       /\                
       | |               
      /\/                
      |.|                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 3 times

** MEMBERS (1 0) (0 1) (1 1) (1 2) (0 3) (:PIVOT 0 1)
   #+begin_example
       /\                
       | |               
      /\/\               
      |.| |              
      \/\/               
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 1) (1 2) (0 3) (0 4) (:PIVOT 0 2)
   #+begin_example
       /\                
       | |               
      /\/                
      | |                
      \/\                
      .| |               
      /\/                
      | |                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 1) (1 2) (:PIVOT 1 0)
   #+begin_example
       /\                
       |.|               
      /\/                
      | |                
      \/\                
       | |               
       \/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 1) (1 2) (:PIVOT 1 1)
   #+begin_example
       /\                
       | |               
      /\/                
      | |.               
      \/\                
       | |               
       \/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (0 1) (1 2) (:PIVOT 1 2)
   #+begin_example
       /\                
       | |               
      /\/                
      | |                
      \/\                
       |.|               
       \/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (1 1) (1 2) (0 3) (0 4) (:PIVOT 0 2)
   #+begin_example
       /\                
       | |               
       \/\               
        | |              
       /\/               
      .| |               
      /\/                
      | |                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (1 1) (1 2) (0 3) (:PIVOT 0 1)
   #+begin_example
       /\                
       | |               
       \/\               
       .| |              
       /\/               
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 3 times

** MEMBERS (1 0) (1 1) (2 1) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
       /\                
       | |               
       \/\/\             
        |.| |            
       /\/\/             
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (1 1) (2 2) (1 3) (2 3) (1 4) (3 4) (0 5) (3 5) (:PIVOT 2 2)
   #+begin_example
       /\                
       | |               
       \/\               
        | |              
        \/\              
         |.|             
        /\/\             
        | | |            
       /\/\/\            
       | | | |           
      /\/  \/\           
      | |   | |          
      \/    \/           
   #+end_example                    
   occurs: 5 times

** MEMBERS (1 0) (2 0) (0 1) (2 1) (1 2) (2 2) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/\             
      | |.| |            
      \/\/\/             
       | | |             
       \/\/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (2 0) (0 1) (2 1) (1 2) (2 2) (:PIVOT 3 5)
   #+begin_example
       /\/\              
       | | |             
      /\/\/\             
      | | | |            
      \/\/\/             
       | | |             
       \/\/              
             .           
   #+end_example                    
   occurs: 2 times

** MEMBERS (1 0) (2 0) (1 1) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
       \/\/              
        |.|              
       /\/               
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 0) (2 0) (3 0) (0 1) (1 1) (2 1) (3 1) (0 2) (2 2) (4 2) (0 3) (1 3) (2 3) (3 3) (0 4) (2 4) (4 4) (:PIVOT 2 2)
   #+begin_example
       /\/\/\            
       | | | |           
      /\/\/\/\           
      | | | | |          
     /\/\/\/\/\          
     | | |.| | |         
     \/\/\/\/\/          
      | | | | |          
     /\/\/\/\/\          
     | | | | | |         
     \/  \/  \/          
   #+end_example                    
   occurs: 2 times

** MEMBERS (1 0) (2 0) (3 0) (0 1) (3 1) (0 2) (4 2) (0 3) (3 3) (1 4) (2 4) (3 4) (:PIVOT 8 6)
   #+begin_example
       /\/\/\            
       | | | |           
      /\/\/\/\           
      | |   | |          
     /\/    \/\          
     | |     | |         
     \/\    /\/          
      | |   | |          
      \/\/\/\/           
       | | | |           
       \/\/\/            
                      .  
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (0 1) (1 0) (2 0) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/              
      | |.|              
      \/\/               
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (0 1) (2 0) (2 2) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
      /\/\/              
      | |.|              
      \/\/\              
         | |             
         \/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (0 1) (2 0) (3 0) (:PIVOT 1 1)
   #+begin_example
         /\/\            
         | | |           
      /\/\/\/            
      | |.|              
      \/\/               
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (0 1) (2 1) (2 0) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
      /\/\/\             
      | |.| |            
      \/\/\/             
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (0 1) (2 1) (3 0) (:PIVOT 1 1)
   #+begin_example
           /\            
           | |           
      /\/\/\/            
      | |.| |            
      \/\/\/             
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (1 0) (0 1) (0 2) (:PIVOT 0 1)
   #+begin_example
       /\                
       | |               
      /\/\               
      |.| |              
     /\/\/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 3 times

** MEMBERS (1 1) (1 0) (0 1) (:PIVOT 0 0)
   #+begin_example
       /\                
      .| |               
      /\/\               
      | | |              
      \/\/               
   #+end_example                    
   occurs: 3 times

** MEMBERS (1 1) (2 0) (1 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/              
      | |.|              
     /\/\/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 1) (2 0) (1 0) (0 1) (:PIVOT 1 0)
   #+begin_example
       /\/\              
       |.| |             
      /\/\/              
      | | |              
      \/\/               
   #+end_example                    
   occurs: 3 times

** MEMBERS (1 2) (0 1) (2 0) (1 0) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/              
      | |.               
     /\/\                
     | | |               
     \/\/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 2) (1 1) (1 0) (0 1) (0 2) (:PIVOT 0 1)
   #+begin_example
       /\                
       | |               
      /\/\               
      |.| |              
     /\/\/               
     | | |               
     \/\/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (1 4) (0 3) (1 0) (1 1) (1 2) (:PIVOT 0 2)
   #+begin_example
       /\                
       | |               
       \/\               
        | |              
       /\/               
      .| |               
      /\/                
      | |                
      \/\                
       | |               
       \/                
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 0) (0 1) (2 2) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
      /\ \/              
      | |.               
      \/ /\              
         | |             
         \/              
   #+end_example                    
   occurs: 2 times

** MEMBERS (2 0) (0 1) (2 2) (:PIVOT 1 6)
   #+begin_example
         /\              
         | |             
      /\ \/              
      | |                
      \/ /\              
         | |             
         \/              
        .                
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 0) (1 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/              
      | |.               
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 3 times

** MEMBERS (2 0) (1 0) (0 1) (:PIVOT 1 0)
   #+begin_example
       /\/\              
       |.| |             
      /\/\/              
      | |                
      \/                 
   #+end_example                    
   occurs: 3 times

** MEMBERS (2 0) (1 1) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
      /\/\/              
      | |.|              
     /\/\/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 3 times

** MEMBERS (2 0) (1 1) (1 2) (0 3) (0 4) (:PIVOT 1 2)
   #+begin_example
         /\              
         | |             
        /\/              
        | |              
       /\/               
       |.|               
      /\/                
      | |                
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 0) (1 1) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
        /\/              
        |.|              
       /\/               
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 3 times

** MEMBERS (2 0) (2 1) (2 2) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
         \/\             
         .| |            
       /\/\/             
       | | |             
      /\/\/              
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 0) (3 0) (:PIVOT 0 0)
   #+begin_example
         /\/\            
      .  | | |           
         \/\/            
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 1) (1 1) (1 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\                
       | |               
      /\/\/\             
      | |.| |            
     /\/\/\/             
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 1) (2 0) (1 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/\             
      | |.| |            
     /\/  \/             
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 1) (2 0) (1 0) (0 1) (:PIVOT 1 0)
   #+begin_example
       /\/\              
       |.| |             
      /\/\/\             
      | | | |            
      \/  \/             
   #+end_example                    
   occurs: 3 times

** MEMBERS (2 1) (2 0) (1 1) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
        /\/\             
        |.| |            
       /\/\/             
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 2) (1 1) (1 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\                
       | |               
      /\/\               
      | |.|              
     /\/\/\              
     | | | |             
     \/  \/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 2) (1 1) (2 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
      /\/\/              
      | |.|              
     /\/\/\              
     | | | |             
     \/  \/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 2) (1 1) (2 0) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
         /\              
         | |             
        /\/              
        |.|              
       /\/\              
       | | |             
      /\/\/              
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (2 2) (2 1) (2 0) (1 0) (0 1) (:PIVOT 1 1)
   #+begin_example
       /\/\              
       | | |             
      /\/\/\             
      | |.| |            
      \/ /\/             
         | |             
         \/              
   #+end_example                    
   occurs: 1 times

** MEMBERS (3 0) (2 0) (1 0) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
       /\/\/\            
       | | | |           
      /\/\/\/            
      | |.               
     /\/                 
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (3 0) (2 0) (1 1) (0 1) (0 2) (:PIVOT 1 1)
   #+begin_example
         /\/\            
         | | |           
      /\/\/\/            
      | |.|              
     /\/\/               
     | |                 
     \/                  
   #+end_example                    
   occurs: 1 times

** MEMBERS (3 0) (2 0) (1 1) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
         /\/\            
         | | |           
        /\/\/            
        |.|              
       /\/               
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

** MEMBERS (3 0) (2 1) (1 1) (1 2) (0 3) (:PIVOT 1 1)
   #+begin_example
           /\            
           | |           
        /\/\/            
        |.| |            
       /\/\/             
       | |               
      /\/                
      | |                
      \/                 
   #+end_example                    
   occurs: 1 times

* Known or Probable Phrases of Power 

We are given:

- Ei!

Checking the maps, several spell out words which are most likely "phrases of
power":

- Ei! (problem 1)
- Ia! Ia! (problem 3)
- R'lyeh (problem 5)
- Yuggoth (problem 7)

** Sniffing out words

First attempt for a word use.

(submit 0 0 "ei!!!!!!" "Ei! test")

This received 307 points and had a significant impact on our standings (which
suggests that there are many teams struggling).

We also recorded one use of a power word.  It is marked in the total rankings
and in the rankings for the problem.

#+BEGIN_EXAMPLE
  Point explanation:

  - size = 1
  - ls = 0
  - ls_old = 0

  This totals to 1 point for locking in the unit.

  - length of phrase = 3
  - reps = 1

  We get a power bonus of 300 because we used a phrase.

  This totals to 2*3*1 + 300 = 306

  This makes the grand total _307_
#+END_EXAMPLE

I submitted a blank command set and it erased all of that.

I did a submission with several "Ei!" phrases in it.

(submit 0 0 "eeei! ei! ei! ei! ei! " "many ei!s")

This scored 331.

#+BEGIN_EXAMPLE
  Point explanation:

  - size = 1
  - ls = 0
  - ls_old = 0

  This totals to 1 point for locking in the unit.

  - length of phrase = 3
  - reps = 5

  We get a power bonus of 300 because we used a phrase.

  This totals to 2*3*5 + 300 = 330

  This makes the grand total _331_
#+END_EXAMPLE

* Game interface
  After loading the project, run =(icfp-2015-cl::start-server)=, then navigate
  your browser to http://localhost:8888 it will start the game.
  WASD moves pieces, arrows rotate pieces (not implemented yet).  See server.lisp
  for more details.
